name: send slack when fails

on: workflow_dispatch

jobs: 
  
  fails_and_slack:

    runs-on: ubuntu-latest

    steps: 

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

   # - name: value error
     # run: |
      # python raise ValueError('A very specific bad thing happened.')
       
    - name: send slack notifiction
      uses: ravsamhq/notify-slack-action@v1
      if: always()
      with:
        status: ${{ job.status }} 
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
